SET(OS_WINDOWS FALSE)
SET(OS_BSD_FAMILY FALSE)
SET(OS_FREEBSD FALSE)
SET(OS_OPENBSD FALSE)
SET(OS_NETBSD FALSE)
SET(OS_LINUX FALSE)
SET(OS_MACOS FALSE)    

IF(${CMAKE_SYSTEM} MATCHES "Windows")
    SET(OS_WINDOWS TRUE)
ENDIF(${CMAKE_SYSTEM} MATCHES "Windows")

IF(${CMAKE_SYSTEM} MATCHES "FreeBSD")
    SET(OS_FREEBSD TRUE)
    SET(OS_BSD_FAMILY TRUE)
ENDIF(${CMAKE_SYSTEM} MATCHES "FreeBSD")

IF (${CMAKE_SYSTEM} MATCHES "OpenBSD")
    SET(OS_OPENBSD TRUE)
    SET(OS_BSD_FAMILY TRUE)
ENDIF (${CMAKE_SYSTEM} MATCHES "OpenBSD")

IF (${CMAKE_SYSTEM} MATCHES "NetBSD")
    SET(OS_NETBSD TRUE)
    SET(OS_BSD_FAMILY TRUE)
ENDIF (${CMAKE_SYSTEM} MATCHES "NetBSD")

IF (${CMAKE_SYSTEM} MATCHES "Linux")
    SET(OS_LINUX TRUE)
ENDIF (${CMAKE_SYSTEM} MATCHES "Linux")

IF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    SET(OS_MACOS TRUE)
    SET(OS_BSD_FAMILY TRUE)
ENDIF(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")

IF(OS_LINUX)
   add_definitions( -DOS_LINUX )
ENDIF(OS_LINUX)

IF(OS_WINDOWS)
   add_definitions( -DOS_WINDOWS )
ENDIF(OS_WINDOWS)

IF(OS_MACOS)
   add_definitions( -DOS_MACOS )
ENDIF(OS_MACOS)